### ISSUE TITLE
Create a reusable Card component

### ISSUE THREAD

**Issue by thibmaek** [inthepocket/white-label-event-app#15]
A Card component will be reused in the overview, personal schedule etc.

We need a generic stateless card component that we can include throughout the application

The signature (props) of this card looks like:
- [ ] a title string ("React Native & Firebase") to be passed as children
- [ ] a timeslot object prop with keys "from" & "to". Both values for these keys are valid js dates to be used as the date to display on the card
- [ ] an optional label string prop to be used as a room, tag, field of interest
- [ ] an optional author string prop to be used to display the author, performer & presenter
- [ ] an optional boolean prop favorite, which if passed should show a star that takes an action.
- [ ] an optional prop onPress to link to the detail screen for the card if it is pressed (for: https://github.com/inthepocket/white-label-event-app/issues/11)
- [ ] the optional prop image which can be a string or object to show an image as overlay for the card https://github.com/inthepocket/white-label-event-app/issues/7)

![gitscout-image-from-clipboard-3](http://static.gitscout.com/acf5816979d269d6188e93b4768962dc9273525556a2c3ecb3b5515482142e64.png)

**Static type:**
```typescript
type TCardProps = {
  children: React.Element<Text> | string,
  timeslot: {
    from: Date,
    to: Date,
  },
  label?: string,
  author?: string,
  favorite?: boolean,
  onPress?: Function,
  image: string | {
    uri: string,
    width: number,
    height: number,
  },
}
```

**Comment by sharonvanhove** [comment]
We'll try this one
