### ISSUE TITLE
Create a reusable Heading component

### ISSUE THREAD

**Issue by thibmaek** [inthepocket/white-label-event-app#16]
A Heading component will be reused in the overview, event detail, etc.

We need a generic stateless heading component that we can include throughout the application

The signature (props) of this component looks like:
- [ ] a title string (like "React Native & Firebase"), passed to the component as children
- [ ] an optional label string (like "Tech") to be used as a label above the component; Passed as a prop

![gitscout-image-from-clipboard-1](http://static.gitscout.com/346a0bc80f143f16a28a18bfeee2f380f7d50978e0c1ee23fc1884073c5be470.png)

**Static type:**
```typescript
type THeadingProps = {
  children: React.Element<Text> | string,
  label?: string,
}
```

**Comment by LHofman** [comment]
I'll take this on.
