### ISSUE TITLE
Create a reusable custom Button component

### ISSUE THREAD

**Issue by thibmaek** [inthepocket/white-label-event-app#18]
React Native already provides a built-in platform-specific [Button component](https://facebook.github.io/react-native/docs/button.html#docsNav). We rarely want to use this, and instead, want our own custom Button component so we can style it and adjust behavior to our liking.

We need a generic stateless button component that we can include throughout the application. Custom buttons are mostly a combination of the built-in View & [Touchable component](https://facebook.github.io/react-native/docs/handling-touches.html#touchables)

This button should have:
- [ ] the option to display text, or if no prop is available just show 'Press me',
- [ ] the option to set the level of the button ('info', 'success', 'warning', 'error') and default to 'info' if no level was passed as a prop
- [ ] the option to pass a function as a prop so the button executes this function when pressed. If no function is passed, the button should just execute `() => {}` (a no-op) as the function.
- [ ] default styling for each level and the option to pass more styles to the button next to the default style currently active.

Ideally, after this custom component is written, it should have its own snapshot unit test to see if it behaves as required. See https://github.com/inthepocket/white-label-event-app/issues/19

```typescript
type TButtonProps = {
  children?: React.Element<Text> | string,
  level?: 'info' | 'success' | 'warning' | 'error',
  onPress: Function,
  style?: StyleSheet,
}
```

**Comment by piere129** [comment]
claimed

**Comment by Jeremy-vdw** [comment]
Claimed!
