### ISSUE TITLE
Add google authentication

### ISSUE THREAD

**Issue by easybird** [inthepocket/white-label-event-app#3]
Docs: https://docs.expo.io/versions/latest/sdk/google.html

**Comment by thibmaek** [comment]
Roughly the same implementation as Facebook, which we already have in place: https://github.com/inthepocket/white-label-event-app/blob/master/utils/authenticationService.js#L4

**Comment by gdm-1718-jerobern** [comment]
Google authentication: in progress ✔

**Comment by easybird** [comment]
@gdm-1718-jerobern in case of questions or remarks, you can always reach out to us through this Discord channel: https://discord.gg/MHHFZdC
