### ISSUE TITLE
Navigation: dedicated screen per track

### ISSUE THREAD

**Issue by tvhitp** [inthepocket/white-label-event-app#36]
**Context:** As a user, I can navigate through the different tracks of the event
**Acceptance criteria:**

- The tracks are displayed as separate screens
- The user can navigate by swiping horizontally
- The order is fixed through the API (later via the user preferred tracks -> separate story)

**Comment by mikeverf** [comment]
Started on animation for pagination, but is out of this scope of this ticket; will make new ticket for animation
