### ISSUE TITLE
Use Authentication methods provided by Firebase

### ISSUE THREAD

**Issue by thibmaek** [inthepocket/white-label-event-app#37]
Currently we are using Expo SDK to log in with Facebook & Google. This works, but since we're already using Firebase it would be best to migrate all our services to this end and not rely on creating an extra Google App _just_ for authentication.

**Comment by GielDeClercq** [comment]
Wij nemen dit

**Comment by thibmaek** [comment]
Closing this because Firebase authentication using the Web SDK from Firebase does not seem possible at the team, we'll continue using Expo in combination with Async Storage
