### ISSUE TITLE
Use named colors from Zeplin instead of abstract colors

### ISSUE THREAD

**Issue by thibmaek** [inthepocket/white-label-event-app#52]
Wherever there is `COLORS.pink` etc, instead replace these constant names on the COLORS object with the named colors from the Zeplin styleguide.

This way we are consistent across design & dev and everybody is talking about the same thing.

![image](https://user-images.githubusercontent.com/6213695/37218209-085e7ba0-23c0-11e8-9599-2218aa28a88b.png)

**Comment by thibmaek** [comment]
I don't see a PR fixing this issue

**Comment by mikeverf** [comment]
Sorry, it’s in the “fix touch not working on touchables bug” commit on PR for #36c didn’t seem worthy of a separate feature branch

**Comment by thibmaek** [comment]
No worries, better to put it in your "this pr closes" line in that PR then, since that puts a reference in this ticket to that PR and auto closes it 😉

**Comment by mikeverf** [comment]
Okay, will do :)
