### ISSUE TITLE
Schedule navigation header design

### ISSUE THREAD

**Issue by mikeverf** [inthepocket/white-label-event-app#57]
### Context

> It's not clear what to do with the navigation header on the schedule page when you start scrolling. For now, a semi-transparent background was added for visibility.

Same goes for the personal schedule (second screenshot).

@jonasleupe
![simulator screen shot - iphone x - 2018-03-13 at 17 46 25](https://user-images.githubusercontent.com/19315705/37356698-dae5a804-26e6-11e8-9f66-3a4d29156dc7.png)

![simulator screen shot - iphone x - 2018-03-13 at 17 48 31](https://user-images.githubusercontent.com/19315705/37356708-df22bbbe-26e6-11e8-8b9b-93013cfef4b9.png)

**Comment by thibmaek** [comment]
On second thought it's better to discuss again with product and make a story out of this later
