### ISSUE TITLE
Display my personal schedule

### ISSUE THREAD

**Issue by tvhitp** [inthepocket/white-label-event-app#9]
**Context:** When I want to see my personal schedule, I can do that easily in the app
**Acceptance criteria:**
- At the bottom of the app a floating button is present: My schedule
- If selected, a modal opens from below with only my sessions listed
- In this list, I can deselect a session
-- When deselecting a session, the list is updated
- My schedule can be left by tapping the exit button
- When no sessions are added yet, the button is disabled

**Comment by thibmaek** [comment]
@mikeverf :
> When no sessions are added yet, the button is disabled

Is this already the case? Then this ticket could be closed :)

**Comment by mikeverf** [comment]
There is disabled state for the button, but it’s never on because the data isn’t dynamically loaded

**Comment by thibmaek** [comment]
Good! If it's disabled this ticket is fine to close since the date is an external dep. to this ticket.
